POST http://localhost:5000/api/cart
   Content-Type: application/json

   {
      "product_id": "0fb0cb7e-d8c4-4708-9765-31cbd8dec0ba",
      "user_id": "0cc48aa0-e7fe-4b70-b39a-abce282a67d8",
      "quantity": "2"
   }

###

GET http://localhost:5000/api/cart/0cc48aa0-e7fe-4b70-b39a-abce282a67d8

###

PATCH http://localhost:5000/api/cart/0fb0cb7e-d8c4-4708-9765-31cbd8dec0ba/0cc48aa0-e7fe-4b70-b39a-abce282a67d8
  Content-Type: application/json

  {
      "product_id": "0fb0cb7e-d8c4-4708-9765-31cbd8dec0ba",
      "user_id": "0cc48aa0-e7fe-4b70-b39a-abce282a67d8",
      "quantity": "6"
  }

###

DELETE http://localhost:5000/api/cart/0fb0cb7e-d8c4-4708-9765-31cbd8dec0ba/0cc48aa0-e7fe-4b70-b39a-abce282a67d8
