POST http://localhost:5000/api/images
   Content-Type: application/json

   {
       "name": "Pancakes",
       "url": "https://i.pinimg.com/736x/bb/38/8f/bb388f316a2a98e5367ba29f6fbb81a1.jpg"

   }

###

GET http://localhost:5000/api/images/2

###

PATCH http://localhost:5000/api/images/2
  Content-Type: application/json

  {
       "name": "Croissants",
       "url": "https://i.pinimg.com/1200x/44/8d/32/448d32d4587586401fa209932344a126.jpg"
  }

###

DELETE http://localhost:5000/api/images/2


